/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/drRf8tiWGKG
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import * as k8s from "@kubernetes/client-node";
import {
  CardTitle,
  CardHeader,
  CardContent,
  Card,
  CardDescription,
} from "@/components/ui/card";
import { JobDetails } from "./job-details";

export default function JobsList({ jobs }: { jobs: k8s.V1Job[] }) {
  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Running Jobs</CardTitle>
        <CardDescription>
          The active jobs that you execute in the Jupyter notebook.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {jobs.map((job) => (
            <JobDetails job={job} key={job.metadata?.name} />
          ))}
          {/* <div className="flex items-center justify-between border-b pb-4">
            <div className="flex items-center gap-2">
              <CircleCheckIcon className="h-5 w-5 text-green-500" />
              <div>
                <h4 className="font-medium">backup-database</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Completed
                </p>
              </div>
            </div>
            <div className="text-sm text-gray-500 dark:text-gray-400">
              <p>2m 34s</p>
              <p>2:15 PM</p>
            </div>
          </div>
          <div className="flex items-center justify-between border-b pb-4">
            <div className="flex items-center gap-2">
              <CircleXIcon className="h-5 w-5 text-red-500" />
              <div>
                <h4 className="font-medium">update-config</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Failed
                </p>
              </div>
            </div>
            <div className="text-sm text-gray-500 dark:text-gray-400">
              <p>1m 12s</p>
              <p>3:45 PM</p>
            </div>
          </div>
          <div className="flex items-center justify-between border-b pb-4">
            <div className="flex items-center gap-2">
              <ClockIcon className="h-5 w-5 text-yellow-500" />
              <div>
                <h4 className="font-medium">migrate-data</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Pending
                </p>
              </div>
            </div>
            <div className="text-sm text-gray-500 dark:text-gray-400">
              <p>-</p>
              <p>4:30 PM</p>
            </div>
          </div>
          <div className="flex items-center justify-between border-b pb-4">
            <div className="flex items-center gap-2">
              <CheckIcon className="h-5 w-5 text-green-500" />
              <div>
                <h4 className="font-medium">generate-reports</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Succeeded
                </p>
              </div>
            </div>
            <div className="text-sm text-gray-500 dark:text-gray-400">
              <p>5m 22s</p>
              <p>9:00 AM</p>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <CircleCheckIcon className="h-5 w-5 text-green-500" />
              <div>
                <h4 className="font-medium">cleanup-logs</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Completed
                </p>
              </div>
            </div>
            <div className="text-sm text-gray-500 dark:text-gray-400">
              <p>3m 45s</p>
              <p>11:30 AM</p>
            </div>
          </div> */}
        </div>
      </CardContent>
    </Card>
  );
}

// function CheckIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M20 6 9 17l-5-5" />
//     </svg>
//   );
// }

// function CircleCheckIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="12" cy="12" r="10" />
//       <path d="m9 12 2 2 4-4" />
//     </svg>
//   );
// }

// function CircleXIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="12" cy="12" r="10" />
//       <path d="m15 9-6 6" />
//       <path d="m9 9 6 6" />
//     </svg>
//   );
// }

// function ClockIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="12" cy="12" r="10" />
//       <polyline points="12 6 12 12 16 14" />
//     </svg>
//   );
// }
