"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qGmgdpvuukB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { ResponsiveLine } from "@nivo/line";

export function JobRuns(props: {
  transformed: Array<{ x: string; y: number }>;
}) {
  return (
    <Card className="h-full w-full">
      <CardHeader>
        <CardTitle>Jobs activity</CardTitle>
        <CardDescription>
          Your jobs executed over the past 7 days
        </CardDescription>
      </CardHeader>
      <CardContent>
        <LineChart className="aspect-[9/4]" data={props.transformed} />
      </CardContent>
    </Card>
  );
}

function LineChart(
  props: React.ComponentProps<"div"> & { data: { x: string; y: number }[] }
) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "jobs",
            data: props.data,
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  );
}
