/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rUORVionfky
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import {
  CardContent,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { User } from "next-auth";

export function UserInfo(props: { user: User; className?: string }) {
  return (
    <Card className={props.className}>
      <CardHeader>
        <CardTitle>User</CardTitle>
        <CardDescription>Your account information.</CardDescription>
      </CardHeader>
      <CardContent className="flex items-center gap-4">
        <Avatar className="h-16 w-16">
          <AvatarImage alt="@shadcn" src={props.user.image!} />
          <AvatarFallback>JD</AvatarFallback>
        </Avatar>
        <div className="space-y-1">
          <h4 className="text-lg font-medium">{props.user.name}</h4>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            {props.user.email}
          </p>
          {/* <p className="text-sm text-gray-500 dark:text-gray-400">
            Passionate about design and technology. Loves building beautiful and functional user interfaces.
          </p> */}
        </div>
      </CardContent>
    </Card>
  );
}
